export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const DISPLAY_ALERT_DUPLICATE_EMAIL = 'DISPLAY_ALERT_DUPLICATE_EMAIL'
export const DISPLAY_ALERT_EMAIL = 'DISPLAY_ALERT_EMAIL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PLAYER_BEGIN = 'CREATE_PLAYER_BEGIN'
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS'
export const CREATE_PLAYER_ERROR = 'CREATE_PLAYER_ERROR'

export const GET_PLAYERS_BEGIN = 'GET_PLAYERS_BEGIN'
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS'

export const GET_ATTACKER_PLAYERS_BEGIN = 'GET_ATTACKER_PLAYERS_BEGIN'
export const GET_ATTACKER_PLAYERS_SUCCESS = 'GET_ATTACKER_PLAYERS_SUCCESS'

export const GET_MIDFIELD_PLAYERS_BEGIN = 'GET_MIDFIELD_PLAYERS_BEGIN'
export const GET_MIDFIELD_PLAYERS_SUCCESS = 'GET_MIDFIELD_PLAYERS_SUCCESS'

export const GET_DEFENSIVE_PLAYERS_BEGIN = 'GET_DEFENSIVE_PLAYERS_BEGIN'
export const GET_DEFENSIVE_PLAYERS_SUCCESS = 'GET_DEFENSIVE_PLAYERS_SUCCESS'

export const GET_GOALKEEPERS_PLAYERS_BEGIN = 'GET_GOALKEEPERS_PLAYERS_BEGIN'
export const GET_GOALKEEPERS_PLAYERS_SUCCESS = 'GET_GOALKEEPERS_PLAYERS_SUCCESS'

export const SET_EDIT_PLAYER = 'SET_EDIT_PLAYER'
export const RESET_EDIT_PLAYER = 'RESET_EDIT_PLAYER'

export const DELETE_PLAYER_BEGIN = 'DELETE_PLAYER_BEGIN'

export const EDIT_PLAYER_BEGIN = 'EDIT_PLAYER_BEGIN'
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS'
export const EDIT_PLAYER_ERROR = 'EDIT_PLAYER_ERROR'
 
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
 


/*  ------------TEAMTRAINING------------ */


export const CREATE_TEAMTRAINING_BEGIN = 'CREATE_TEAMTRAINING_BEGIN'
export const CREATE_TEAMTRAINING_SUCCESS = 'CREATE_TEAMTRAINING_SUCCESS'
export const CREATE_TEAMTRAINING_ERROR = 'CREATE_TEAMTRAINING_ERROR'

export const GET_TEAMTRAININGS_BEGIN = 'GET_TEAMTRAININGS_BEGIN'
export const GET_TEAMTRAININGS_SUCCESS = 'GET_TEAMTRAININGS_SUCCESS'